namespace InvoiceTrackingSystemBackend.Entities.Vega;

/// <summary>VEGA ERP - F0102TBLCARI tablosuna karşılık gelen salt-okunur entity.</summary>
public class TblCari
{
    public byte[]? Resim { get; set; }
    public int Ind { get; set; }
    public int? FirmaNo { get; set; }
    public int? EFaturaSenaryo { get; set; }
    public int? KrediLimitiKontrol { get; set; }
    public int? OdemeSekli { get; set; }
    public int? DepoInd { get; set; }
    public int? TaksitTipi { get; set; }
    public int? TaksitGunu { get; set; }
    public int? SatisKarti { get; set; }
    public int? FirmaTipi { get; set; }
    public int? Statu { get; set; }
    public int? Opsiyon { get; set; }
    public int? ZimFiyat { get; set; }
    public int? Status { get; set; }
    public int? PersonelNo { get; set; }
    public int? Depo { get; set; }
    public int? Sektor { get; set; }
    public int? Marka { get; set; }
    public DateTime? KayitTarihi { get; set; }
    public string? Istihbarat { get; set; }
    public string? KefilAdres2 { get; set; }
    public string? KefilAdres1 { get; set; }
    public string? AdresPosta { get; set; }
    public string? AdresFatura { get; set; }
    public string? AdresSevk { get; set; }
    public bool? AskSatisKarti { get; set; }
    public bool? Deleted { get; set; }
    public bool? EFaturaKullanicisi { get; set; }
    public bool? IadeFaturasiKesilmesin { get; set; }
    public bool? TahsilatYapilmasin { get; set; }
    public bool? BagKurCalismasin { get; set; }
    public bool? SatisYapilmasin { get; set; }
    public decimal? RiskLimiti { get; set; }
    public decimal? KrediLimiti { get; set; }
    public decimal? Iskonto { get; set; }
    public decimal? AylikVade { get; set; }
    public decimal? Prim { get; set; }
    public decimal? GecikmeFaizi { get; set; }
    public decimal? OdemeBakiyesi { get; set; }
    public decimal? Bakiye { get; set; }
    public string? Unvan { get; set; }
    public string? Kod3 { get; set; }
    public string? Kod4 { get; set; }
    public string? Kod5 { get; set; }
    public string? Kod1 { get; set; }
    public string? Kod2 { get; set; }
    public string? Email { get; set; }
    public string? Url { get; set; }
    public string? Telefon1 { get; set; }
    public string? Telefon2 { get; set; }
    public string? Soyadi { get; set; }
    public string? Adi { get; set; }
    public string? YDahili { get; set; }
    public string? YTelefon1 { get; set; }
    public string? YTelefon2 { get; set; }
    public string? Telefon3 { get; set; }
    public string? Faks { get; set; }
    public string? Modem { get; set; }
    public string? YModem { get; set; }
    public string? Kefil1 { get; set; }
    public string? Kefil2 { get; set; }
    public string? Pozisyon { get; set; }
    public string? YEmail { get; set; }
    public string? YUrl { get; set; }
    public string? Kefil1Telefon { get; set; }
    public string? Kefil1CepTelefon { get; set; }
    public string? Kefil2Telefon { get; set; }
    public string? Kefil2CepTelefon { get; set; }
    public string? YGsm { get; set; }
    public string? YFaks { get; set; }
    public string? Kefil1TakipKodu { get; set; }
    public string? Kefil2TakipKodu { get; set; }
    public string? Kefil1TcKimlikNo { get; set; }
    public string? Kefil2TcKimlikNo { get; set; }
    public string? FirmaTakipKodu { get; set; }
    public string? ParaBirimi { get; set; }
    public string? Yetkili { get; set; }
    public string? VergiDairesi { get; set; }
    public string? VergiNo { get; set; }
    public string? Il { get; set; }
    public string? Sehir { get; set; }
    public string? Alias { get; set; }
    public string? FirmaKodu { get; set; }
    public string? FirmaAdi { get; set; }
    public decimal? Sermaye { get; set; }
    public string? SicilNo { get; set; }
    public bool? ETicaret { get; set; }
    public DateTime? IseGirisTarihi { get; set; }
    public DateTime? IstenCikisTarihi { get; set; }
    public bool? OdemeYapilmasin { get; set; }
    public string? GrupKodu { get; set; }
    public string? NaceKodu { get; set; }
    public decimal? HedefCiro { get; set; }
    public bool? SmsGonder { get; set; }
    public bool? EmailGonder { get; set; }
    public int? EArsivTeslimTipi { get; set; }
    public string? Kod6 { get; set; }
    public string? Kod7 { get; set; }
    public int? IsletmeTuru { get; set; }
    public string? GlnKodu { get; set; }
    public string? SubeAdi { get; set; }
    public string? Uid { get; set; }
    public bool? KdvMuafiyati { get; set; }
    public int? CariPozisyon { get; set; }
    public bool? AlisYapilmasin { get; set; }
    public bool? SiparisYapilmasin { get; set; }
    public DateTime? GuncellemeTarihi { get; set; }
    public int? KurTipi { get; set; }
    public bool? EIrsaliye { get; set; }
    public string? EIrsaliyeAlias { get; set; }
    public string? UtsKurumNo { get; set; }
    public bool? AliasGuncellenmesin { get; set; }
    public bool? IstihbaratBelgedeGorunsun { get; set; }
    public string? SmEmail { get; set; }
    public string? PostaKodu { get; set; }
    public bool? SmsIzniVar { get; set; }
    public bool? KvkkIzniVar { get; set; }
    public string? StcNo { get; set; }
    public string? Sadi { get; set; }
    public string? SSoyadi { get; set; }
    public string? Plaka { get; set; }
}
