namespace InvoiceTrackingSystemBackend.Constants;

public enum AuthActivityType
{
    REGISTERED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFIED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DEACTIVATED,
    ROLE_DELETED,
    PROFILE_UPDATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    OUT_OF_OFFICE_CHANGED,
    FILE_UPLOADED
}
