// <auto-generated />
using System;
using InvoiceTrackingSystemBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceTrackingSystemBackend.Migrations.InvoiceDb
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20260914075208_AddInvoiceArchiveFields")]
    partial class AddInvoiceArchiveFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RateToTry")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("TCMB");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("uq_exchange_rate_day");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountTry")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Auditor1UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Auditor2UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Try");

                    b.Property<string>("CurrentAccountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ErpCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErpMatchStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ErpSource")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExchangeRateId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InvoiceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("PredictionConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("PredictionModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VknTckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("ExchangeRateId");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VknTckn", "InvoiceNumber", "Amount")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_dedup");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("invoice_activity_logs", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FileSizeBytes")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("SCANNED_SIGNED_PDF");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("NasRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("invoice_attachments", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_line_items", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceNotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("invoice_notification_logs", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RelatedInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("RelatedInvoiceId");

                    b.HasIndex("InvoiceId", "RelatedInvoiceId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_relation");

                    b.ToTable("invoice_relations", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("invoice_types", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDurationDays")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("StepRoleTag")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceTypeId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_invoice_type_step_order");

                    b.ToTable("invoice_type_steps", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStepApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceTypeStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceTypeStepId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("uq_step_approver_priority");

                    b.HasIndex("InvoiceTypeStepId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_step_approver_user");

                    b.ToTable("invoice_type_step_approvers", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_workflow_history", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceTypeStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceTypeStepId");

                    b.HasIndex("DueAt", "CompletedAt")
                        .HasDatabaseName("ix_workflow_steps_due");

                    b.HasIndex("InvoiceId", "CompletedAt")
                        .HasDatabaseName("ix_workflow_steps_current_lookup");

                    b.ToTable("invoice_workflow_steps", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SupplierCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VknTckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCategoryId");

                    b.HasIndex("VknTckn")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.SupplierCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("supplier_categories", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.SupplierInvoiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex("SupplierId", "InvoiceTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_supplier_invoice_type");

                    b.ToTable("supplier_invoice_types", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.WorkflowTransitionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int?>("SourceStepId")
                        .HasColumnType("int");

                    b.Property<int>("TargetStepId")
                        .HasColumnType("int");

                    b.Property<string>("TriggerAction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceStepId");

                    b.HasIndex("TargetStepId");

                    b.HasIndex("TriggerAction", "SourceStepId")
                        .HasDatabaseName("ix_transition_rule_lookup");

                    b.ToTable("workflow_transition_rules", (string)null);
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.ExchangeRate", "ExchangeRate")
                        .WithMany("Invoices")
                        .HasForeignKey("ExchangeRateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceType", "InvoiceType")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExchangeRate");

                    b.Navigation("InvoiceType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceActivityLog", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", "WorkflowStep")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("Invoice");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceAttachment", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("Attachments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", "WorkflowStep")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("Invoice");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceLineItem", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceNotificationLog", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", "WorkflowStep")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("Invoice");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceRelation", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("Relations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "RelatedInvoice")
                        .WithMany("RelatedToRelations")
                        .HasForeignKey("RelatedInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("RelatedInvoice");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceType", "InvoiceType")
                        .WithMany("Steps")
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceType");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStepApprover", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", "InvoiceTypeStep")
                        .WithMany("Approvers")
                        .HasForeignKey("InvoiceTypeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceTypeStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowHistory", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", "Invoice")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", "InvoiceTypeStep")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("InvoiceTypeStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("InvoiceTypeStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Supplier", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.SupplierCategory", "SupplierCategory")
                        .WithMany("Suppliers")
                        .HasForeignKey("SupplierCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SupplierCategory");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.SupplierInvoiceType", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceType", "InvoiceType")
                        .WithMany("SupplierInvoiceTypes")
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.Supplier", "Supplier")
                        .WithMany("SupplierInvoiceTypes")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.WorkflowTransitionRule", b =>
                {
                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", "SourceStep")
                        .WithMany("SourceTransitionRules")
                        .HasForeignKey("SourceStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", "TargetStep")
                        .WithMany("TargetTransitionRules")
                        .HasForeignKey("TargetStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceStep");

                    b.Navigation("TargetStep");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.ExchangeRate", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Invoice", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Attachments");

                    b.Navigation("LineItems");

                    b.Navigation("NotificationLogs");

                    b.Navigation("RelatedToRelations");

                    b.Navigation("Relations");

                    b.Navigation("WorkflowHistories");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceType", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Steps");

                    b.Navigation("SupplierInvoiceTypes");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceTypeStep", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("SourceTransitionRules");

                    b.Navigation("TargetTransitionRules");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.InvoiceWorkflowStep", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Attachments");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.Supplier", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("SupplierInvoiceTypes");
                });

            modelBuilder.Entity("InvoiceTrackingSystemBackend.Entities.Invoice.SupplierCategory", b =>
                {
                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
